name: Auto-tag
on:
  push:
    branches:
      - master
jobs:
  autotag:
    name: Auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute next tag name
        id: compute_tag
        shell: pwsh
        continue-on-error: true
        run: |
          $lastTag = $(git tag | ForEach-Object { [System.Management.Automation.SemanticVersion]::new($_) } | Sort-Object | Select-Object -Last 1)
          if ([string]::IsNullOrEmpty($lastTag)) {
            $newTag = "1.0.0-pre.1"
          } else {
            if ([string]::IsNullOrEmpty($lastTag.PreReleaseLabel)) {
              $newTag = [System.Management.Automation.SemanticVersion]::new($lastTag.Major, $lastTag.Minor, $lastTag.Patch + 1, "pre.1").ToString()
            } else {
              $newTag = [System.Management.Automation.SemanticVersion]::new($lastTag.Major, $lastTag.Minor, $lastTag.Patch, "pre." + ([int]::Parse($lastTag.PreReleaseLabel.Substring(4)) + 1)).ToString()
            }
          }
          Write-Output "::set-output name=tag_name::$newTag"
        
      - name: Auto-tag repo
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{secrets.GIT_TOKEN}}
          tag: "${{steps.compute_tag.outputs.tag_name}}"
